# Generated by Django 4.2.9 on 2024-03-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
        ),
    ]
