# Generated by Django 4.2.9 on 2024-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_team_delete_participant_alter_post_options_post_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Запис', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
