# Generated by Django 4.2.9 on 2024-03-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_options_remove_post_team_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('coach', models.CharField(max_length=100, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Футбольная команда',
                'verbose_name_plural': 'Футбольные команды',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.footballteam', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Футбольный игрок',
                'verbose_name_plural': 'Футбольные игроки',
            },
        ),
    ]
