# Generated by Django 4.2.9 on 2024-03-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_footballteam_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='FootballTeam',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
